const SITE_URL = 'https://site.earthfast.com'

addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

async function handleRequest(request) {
  const userAgent = request.headers.get('User-Agent') || ''
  const isSpecialAgent = checkIfSpecialAgent(userAgent)

  if (isSpecialAgent) {
    // Serve static HTML for search engine crawlers and link shorteners
    return new Response(getStaticHTML(), {
      headers: { 'Content-Type': 'text/html' },
    })
  } else {
    // Serve the original site content
    return fetch(SITE_URL + new URL(request.url).pathname)
  }
}

function checkIfSpecialAgent(userAgent) {
  // generated from https://github.com/monperrus/crawler-user-agents/blob/master/crawler-user-agents.json
  const specialAgents = [
      "Googlebot\\/",
      "Googlebot-Mobile",
      "Googlebot-Image",
      "Googlebot-News",
      "Googlebot-Video",
      "AdsBot-Google([^-]|$)",
      "AdsBot-Google-Mobile",
      "Feedfetcher-Google",
      "Mediapartners-Google",
      "Mediapartners \\(Googlebot\\)",
      "APIs-Google",
      "Google-InspectionTool",
      "Storebot-Google",
      "GoogleOther",
      "bingbot",
      "Slurp",
      "[wW]get",
      "LinkedInBot",
      "Python-urllib",
      "python-requests",
      "aiohttp",
      "httpx",
      "libwww-perl",
      "httpunit",
      "Nutch",
      "Go-http-client",
      "phpcrawl",
      "msnbot",
      "jyxobot",
      "FAST-WebCrawler",
      "FAST Enterprise Crawler",
      "BIGLOTRON",
      "Teoma",
      "convera",
      "seekbot",
      "Gigabot",
      "Gigablast",
      "exabot",
      "ia_archiver",
      "GingerCrawler",
      "webmon ",
      "HTTrack",
      "grub\\.org",
      "UsineNouvelleCrawler",
      "antibot",
      "netresearchserver",
      "speedy",
      "fluffy",
      "findlink",
      "msrbot",
      "panscient",
      "yacybot",
      "AISearchBot",
      "ips-agent",
      "tagoobot",
      "MJ12bot",
      "woriobot",
      "yanga",
      "buzzbot",
      "mlbot",
      "yandex\\.com\\/bots",
      "purebot",
      "Linguee Bot",
      "CyberPatrol",
      "voilabot",
      "Baiduspider",
      "citeseerxbot",
      "spbot",
      "twengabot",
      "postrank",
      "Turnitin",
      "scribdbot",
      "page2rss",
      "sitebot",
      "linkdex",
      "Adidxbot",
      "ezooms",
      "dotbot",
      "Mail\\.RU_Bot",
      "discobot",
      "heritrix",
      "findthatfile",
      "europarchive\\.org",
      "NerdByNature\\.Bot",
      "sistrix crawler",
      "Ahrefs(Bot|SiteAudit)",
      "fuelbot",
      "CrunchBot",
      "IndeedBot",
      "mappydata",
      "woobot",
      "ZoominfoBot",
      "PrivacyAwareBot",
      "Multiviewbot",
      "SWIMGBot",
      "Grobbot",
      "eright",
      "Apercite",
      "semanticbot",
      "Aboundex",
      "domaincrawler",
      "wbsearchbot",
      "summify",
      "CCBot",
      "edisterbot",
      "SeznamBot",
      "ec2linkfinder",
      "gslfbot",
      "aiHitBot",
      "intelium_bot",
      "facebookexternalhit",
      "Yeti",
      "RetrevoPageAnalyzer",
      "lb-spider",
      "Sogou",
      "lssbot",
      "careerbot",
      "wotbox",
      "wocbot",
      "ichiro",
      "DuckDuckBot",
      "lssrocketcrawler",
      "drupact",
      "webcompanycrawler",
      "acoonbot",
      "openindexspider",
      "gnam gnam spider",
      "web-archive-net\\.com\\.bot",
      "backlinkcrawler",
      "coccoc",
      "integromedb",
      "content crawler spider",
      "toplistbot",
      "it2media-domain-crawler",
      "ip-web-crawler\\.com",
      "siteexplorer\\.info",
      "elisabot",
      "proximic",
      "changedetection",
      "arabot",
      "WeSEE:Search",
      "niki-bot",
      "CrystalSemanticsBot",
      "rogerbot",
      "360Spider",
      "psbot",
      "InterfaxScanBot",
      "CC Metadata Scaper",
      "g00g1e\\.net",
      "GrapeshotCrawler",
      "urlappendbot",
      "brainobot",
      "fr-crawler",
      "binlar",
      "SimpleCrawler",
      "Twitterbot",
      "cXensebot",
      "smtbot",
      "bnf\\.fr_bot",
      "A6-Indexer",
      "ADmantX",
      "Facebot",
      "OrangeBot\\/",
      "memorybot",
      "AdvBot",
      "MegaIndex",
      "SemanticScholarBot",
      "ltx71",
      "nerdybot",
      "xovibot",
      "BUbiNG",
      "Qwantify",
      "archive\\.org_bot",
      "Applebot",
      "TweetmemeBot",
      "crawler4j",
      "findxbot",
      "S[eE][mM]rushBot",
      "yoozBot",
      "lipperhey",
      "Y!J",
      "Domain Re-Animator Bot",
      "AddThis",
      "Screaming Frog SEO Spider",
      "MetaURI",
      "Scrapy",
      "Livelap[bB]ot",
      "OpenHoseBot",
      "CapsuleChecker",
      "collection@infegy\\.com",
      "IstellaBot",
      "DeuSu\\/",
      "betaBot",
      "Cliqzbot\\/",
      "MojeekBot\\/",
      "netEstate NE Crawler",
      "SafeSearch microdata crawler",
      "Gluten Free Crawler\\/",
      "Sonic",
      "Sysomos",
      "Trove",
      "deadlinkchecker",
      "Slack-ImgProxy",
      "Embedly",
      "RankActiveLinkBot",
      "iskanie",
      "SafeDNSBot",
      "SkypeUriPreview",
      "Veoozbot",
      "Slackbot",
      "redditbot",
      "datagnionbot",
      "Google-Adwords-Instant",
      "adbeat_bot",
      "WhatsApp",
      "contxbot",
      "pinterest\\.com\\/bot",
      "electricmonk",
      "GarlikCrawler",
      "BingPreview\\/",
      "vebidoobot",
      "FemtosearchBot",
      "Yahoo Link Preview",
      "MetaJobBot",
      "DomainStatsBot",
      "mindUpBot",
      "Daum\\/",
      "Jugendschutzprogramm-Crawler",
      "Xenu Link Sleuth",
      "Pcore-HTTP",
      "moatbot",
      "KosmioBot",
      "[pP]ingdom",
      "AppInsights",
      "PhantomJS",
      "Gowikibot",
      "PiplBot",
      "Discordbot",
      "TelegramBot",
      "Jetslide",
      "newsharecounts",
      "James BOT",
      "Bark[rR]owler",
      "TinEye",
      "SocialRankIOBot",
      "trendictionbot",
      "Ocarinabot",
      "epicbot",
      "Primalbot",
      "DuckDuckGo-Favicons-Bot",
      "GnowitNewsbot",
      "Leikibot",
      "LinkArchiver",
      "YaK\\/",
      "PaperLiBot",
      "Digg Deeper",
      "dcrawl",
      "Snacktory",
      "AndersPinkBot",
      "Fyrebot",
      "EveryoneSocialBot",
      "Mediatoolkitbot",
      "Luminator-robots",
      "ExtLinksBot",
      "SurveyBot",
      "NING\\/",
      "okhttp",
      "Nuzzel",
      "omgili",
      "PocketParser",
      "YisouSpider",
      "um-LN",
      "ToutiaoSpider",
      "MuckRack",
      "Jamie's Spider",
      "AHC\\/",
      "NetcraftSurveyAgent",
      "Laserlikebot",
      "^Apache-HttpClient",
      "AppEngine-Google",
      "Jetty",
      "Upflow",
      "Thinklab",
      "Traackr\\.com",
      "Twurly",
      "Mastodon",
      "http_get",
      "DnyzBot",
      "botify",
      "007ac9 Crawler",
      "BehloolBot",
      "BrandVerity",
      "check_http",
      "BDCbot",
      "ZumBot",
      "EZID",
      "ICC-Crawler",
      "ArchiveBot",
      "^LCC ",
      "filterdb\\.iss\\.net\\/crawler",
      "BLP_bbot",
      "BomboraBot",
      "Buck\\/",
      "Companybook-Crawler",
      "Genieo",
      "magpie-crawler",
      "MeltwaterNews",
      "Moreover",
      "newspaper\\/",
      "ScoutJet",
      "(^| )sentry\\/",
      "StorygizeBot",
      "UptimeRobot",
      "OutclicksBot",
      "seoscanners",
      "Hatena",
      "Google Web Preview",
      "MauiBot",
      "AlphaBot",
      "SBL-BOT",
      "IAS crawler",
      "adscanner",
      "Netvibes",
      "acapbot",
      "Baidu-YunGuanCe",
      "bitlybot",
      "blogmuraBot",
      "Bot\\.AraTurka\\.com",
      "bot-pge\\.chlooe\\.com",
      "BoxcarBot",
      "BTWebClient",
      "ContextAd Bot",
      "Digincore bot",
      "Disqus",
      "Feedly",
      "Fetch\\/",
      "Fever",
      "Flamingo_SearchEngine",
      "FlipboardProxy",
      "g2reader-bot",
      "G2 Web Services",
      "imrbot",
      "K7MLWCBot",
      "Kemvibot",
      "Landau-Media-Spider",
      "linkapediabot",
      "vkShare",
      "Siteimprove\\.com",
      "BLEXBot\\/",
      "DareBoost",
      "ZuperlistBot\\/",
      "Miniflux\\/",
      "Feedspot",
      "Diffbot\\/",
      "SEOkicks",
      "tracemyfile",
      "Nimbostratus-Bot",
      "zgrab",
      "PR-CY\\.RU",
      "AdsTxtCrawler",
      "Datafeedwatch",
      "Zabbix",
      "TangibleeBot",
      "google-xrawler",
      "axios",
      "Amazon CloudFront",
      "Pulsepoint",
      "CloudFlare-AlwaysOnline",
      "Google-Structured-Data-Testing-Tool",
      "WordupInfoSearch",
      "WebDataStats",
      "HttpUrlConnection",
      "Seekport Crawler",
      "ZoomBot",
      "VelenPublicWebCrawler",
      "MoodleBot",
      "jpg-newsbot",
      "outbrain",
      "W3C_Validator",
      "Validator\\.nu",
      "W3C-checklink",
      "W3C-mobileOK",
      "W3C_I18n-Checker",
      "FeedValidator",
      "W3C_CSS_Validator",
      "W3C_Unicorn",
      "Google-PhysicalWeb",
      "Blackboard",
      "ICBot\\/",
      "BazQux",
      "Twingly",
      "Rivva",
      "Experibot",
      "awesomecrawler",
      "Dataprovider\\.com",
      "GroupHigh\\/",
      "theoldreader\\.com",
      "AnyEvent",
      "Uptimebot\\.org",
      "Nmap Scripting Engine",
      "2ip\\.ru",
      "Clickagy",
      "Caliperbot",
      "MBCrawler",
      "online-webceo-bot",
      "B2B Bot",
      "AddSearchBot",
      "Google Favicon",
      "HubSpot",
      "Chrome-Lighthouse",
      "HeadlessChrome",
      "CheckMarkNetwork\\/",
      "www\\.uptime\\.com",
      "Streamline3Bot\\/",
      "serpstatbot\\/",
      "MixnodeCache\\/",
      "^curl",
      "SimpleScraper",
      "RSSingBot",
      "Jooblebot",
      "fedoraplanet",
      "Friendica",
      "NextCloud",
      "Tiny Tiny RSS",
      "RegionStuttgartBot",
      "Bytespider",
      "Datanyze",
      "Google-Site-Verification",
      "TrendsmapResolver",
      "tweetedtimes",
      "NTENTbot",
      "Gwene",
      "SimplePie",
      "SearchAtlas",
      "Superfeedr",
      "feedbot",
      "UT-Dorkbot",
      "Amazonbot",
      "SerendeputyBot",
      "Eyeotabot",
      "officestorebot",
      "Neticle Crawler",
      "SurdotlyBot",
      "LinkisBot",
      "AwarioSmartBot",
      "AwarioRssBot",
      "RyteBot",
      "FreeWebMonitoring SiteChecker",
      "AspiegelBot",
      "NAVER Blog Rssbot",
      "zenback bot",
      "SentiBot",
      "Domains Project\\/",
      "Pandalytics",
      "VKRobot",
      "bidswitchbot",
      "tigerbot",
      "NIXStatsbot",
      "Atom Feed Robot",
      "[Cc]urebot",
      "PagePeeker\\/",
      "Vigil\\/",
      "rssbot\\/",
      "startmebot\\/",
      "JobboerseBot",
      "seewithkids",
      "NINJA bot",
      "Cutbot",
      "BublupBot",
      "BrandONbot",
      "RidderBot",
      "Taboolabot",
      "Dubbotbot",
      "FindITAnswersbot",
      "infoobot",
      "Refindbot",
      "BlogTraffic\\/\\d\\.\\d+ Feed-Fetcher",
      "SeobilityBot",
      "Cincraw",
      "Dragonbot",
      "VoluumDSP-content-bot",
      "FreshRSS",
      "BitBot",
      "^PHP-Curl-Class",
      "Google-Certificates-Bridge",
      "centurybot",
      "Viber",
      "e\\.ventures Investment Crawler",
      "evc-batch",
      "PetalBot",
      "virustotal",
      "(^| )PTST\\/",
      "minicrawler",
      "Cookiebot",
      "trovitBot",
      "seostar\\.co",
      "IonCrawl",
      "Uptime-Kuma",
      "SeekportBot",
      "FreshpingBot",
      "Feedbin",
      "CriteoBot",
      "Snap URL Preview Service",
      "Better Uptime Bot",
      "RuxitSynthetic",
      "Google-Read-Aloud",
      "Valve\\/Steam",
      "OdklBot\\/",
      "GPTBot",
      "ChatGPT-User",
      "YandexRenderResourcesBot\\/",
      "LightspeedSystemsCrawler",
      "ev-crawler\\/",
      "BitSightBot\\/",
      "woorankreview\\/",
      "Google-Safety",
      "AwarioBot",
      "DataForSeoBot",
      "Linespider",
      "WellKnownBot",
      "A Patent Crawler",
      "StractBot",
      "search\\.marginalia\\.nu",
      "YouBot",
      "Nicecrawler",
      "Neevabot",
      "BrightEdge Crawler",
      "SiteCheckerBotCrawler",
      "TombaPublicWebCrawler",
      "CrawlyProjectCrawler",
      "KomodiaBot",
      "KStandBot",
      "CISPA Webcrawler",
      "MTRobot",
      "hyscore\\.io",
      "AlexandriaOrgBot",
      "2ip bot",
      "Yellowbrandprotectionbot",
      "SEOlizer",
      "vuhuvBot",
      "INETDEX-BOT",
      "Synapse",
      "t3versionsBot",
      "deepnoc",
      "Cocolyzebot",
      "hypestat",
      "ReverseEngineeringBot",
      "sempi\\.tech",
      "Iframely",
      "MetaInspector",
      "node-fetch",
      "lkxscan",
      "python-opengraph",
      "OpenGraphCheck",
      "developers\\.google\\.com\\/\\+\\/web\\/snippet",
      "SenutoBot",
      "MaCoCu",
      "NewsBlur",
      "inoreader",
      "NetSystemsResearch",
      "PageThing",
      "WordPress\\/",
      "PhxBot",
      "ImagesiftBot",
      "Expanse",
      "InternetMeasurement",
      "^BW\\/",
      "GeedoBot",
      "Audisto Crawler",
      "PerplexityBot\\/",
      "[cC]laude[bB]ot",
      "Monsidobot",
      "GroupMeBot"
  ]
  return specialAgents.some(agent => 
    RegExp(agent).test(userAgent) || userAgent.toLowerCase().includes(agent)
  )
}

function getStaticHTML() {
  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preload" href="/_next/static/media/a34f9d1faa5f3315-s.p.woff2" as="font" crossorigin="" type="font/woff2"/>
        <link rel="preload" href="/_next/static/media/92f44bb82993d879-s.p.woff2" as="font" crossorigin="" type="font/woff2"/>
        <link rel="stylesheet" href="/_next/static/css/c859332d38b378a2.css" data-precedence="next"/>
        <link rel="stylesheet" href="/_next/static/css/3737962d55064c7a.css" data-precedence="next"/>
        <link rel="preload" as="script" fetchPriority="low" href="/_next/static/chunks/webpack-1aa1aa9164d4f5e9.js"/>
        <script src="/_next/static/chunks/fd9d1056-ba964eff9d7f2627.js" async=""></script><script src="/_next/static/chunks/23-e32fad52fa4c6047.js" async=""></script><script src="/_next/static/chunks/main-app-c2b12c2ff48a97f6.js" async=""></script><script src="/_next/static/chunks/94730671-1851de766501d70f.js" async=""></script><script src="/_next/static/chunks/795d4814-08cde1cb947debde.js" async=""></script><script src="/_next/static/chunks/f25cdb8d-77198f3dcc46fa8f.js" async=""></script><script src="/_next/static/chunks/385cb88d-b045e71d9de0a278.js" async=""></script><script src="/_next/static/chunks/53c13509-dcd24fe02396565a.js" async=""></script><script src="/_next/static/chunks/0e762574-b52d3c6ab8a30710.js" async=""></script><script src="/_next/static/chunks/830-0fbd90cd31752c8c.js" async=""></script><script src="/_next/static/chunks/app/page-9467fe62cd9d431e.js" async=""></script>
        <link rel="icon" href="/favicon.ico" sizes="any"/>
        <title>EarthFast - Decentralize your frontend, securely.</title>
        <meta name="description" content="EarthFast is an infrastructure protocol that shifts the responsibility of updating, deploying and hosting your frontend to a community of voters."/>
        <link rel="icon" href="/icon.ico" media="(prefers-color-scheme: light)"/>
        <link rel="icon" href="/icon-dark.ico" media="(prefers-color-scheme: dark)"/>
        <meta name="next-size-adjust"/>
        <script src="/_next/static/chunks/polyfills-78c92fac7aa8fdd8.js" noModule=""></script>
        <meta property="og:title" content="EarthFast - Decentralize your frontend, securely.">
        <meta property="og:description" content="EarthFast is an infrastructure protocol that shifts the responsibility of updating, deploying and hosting your frontend to a community of voters.">
        <meta property="og:image" content="https://cdn.jsdelivr.net/gh/earthfast/landing-site/public/dark-logo.png">
        <meta property="og:url" content="https://earthfast.com">
        <meta name="twitter:card" content="summary_large_image">
    </head>
    </html>
  `
}